### ISSUE TITLE
Duplicate GitHub followers batch in Profile

### ISSUE THREAD

**Issue by verma-kunal** [Rishit-dagli/Rishit-dagli#7]
Suggested to hide the GitHub followers batch, as its already visible on GitHub

![Screenshot 2021-05-28 at 10 13 51 PM](https://user-images.githubusercontent.com/72245772/120016255-fdc55380-c001-11eb-8fd7-94d43a505560.png)

**Comment by Amisha328** [comment]
May I do this task?

**Comment by Rishit-dagli** [comment]
Thanks for raising this issue and sorry for missing it, this got swarmed in the GitHub notifications.

I agree that GitHub followers are already visible on GitHub UI, but I strongly feel that since this mentions some of my major social links, I should still include GitHub for completeness regardless of the duplication.

I will close this issue for now, if you feel otherwise feel free to reopen the issue.
